apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership
    spec:
      imagePullSecrets:
        - name: ibm-cr-secret
      containers:
        - image: br.icr.io/sn-labs-kaianmateus/dealership:latest
          imagePullPolicy: Always
          name: dealership
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
